### ISSUE TITLE
Deal with the `www.` prefix in internal page links

### ISSUE THREAD

**Issue by fnesveda** [jancurn/actor-find-broken-links#8]
When inspecting a website, if you insert its URL with `www.` in the beginning, like `https://www.apify.com/`, but the internal links don't have the `www.` prefix, like `https://apify.com/about`, they do not get enqueued for recursive inspection, even though they are technically nested pages of the main page. We should consider adding some logic that deals with this and maybe ignores the `www.` prefix at the start of the URL when considering whether to recursively check a link, or not.

**Comment by jancurn** [comment]
In principle, we should have a better way to specify pages compared to start URLs and pseudo-URLs paradigm, as discussed on Slapy team building.
